from enum import Enum

class DiagnosticCode(Enum):
    """Diagnostic codes used by the Falx lexer, parser and runtime"""
    # Runtime errors
    UNDEFINED_VARIABLE = "E1000"
    UNDEFINED_PROPERTY = "E1001"
    INVALID_OPERATION = "E1002"
    DIVISION_BY_ZERO = "E1003"
    ASSIGN_TO_CONSTANT = "E1004"
    VARIABLE_ALREADY_EXISTS = "E1005"
    RECURSION_DEPTH_EXCEEDED = "E1024"
    OBJECT_NOT_ITERABLE = "E1025"
    ASSERTION_FAILED = "E1027"
    IMMUTABLE_VALUE = "E1028"
    DESTRUCTURE_COUNT_MISMATCH = "E1029"

    # Type errors
    UNEXPECTED_TYPE = "E1026"

    # Operational errors
    CANNOT_MULTIPLY_BY = "E1006"
    CANNOT_DIVIDE_BY = "E1007"
    CANNOT_ADD_WITH_VALUE = "E1008"
    CANNOT_MOD_WITH_VALUE = "E1009"
    CANNOT_COMPARE_TO = "E1010"
    CANNOT_CONVERT_TO_TYPE = "E1011"
    CANNOT_EVALUATE_VALUE = "E1015"
    CANNOT_MINUS_FROM_VALUE = "E1019"
    CANNOT_INVERT_VALUE = "E1030"

    # Property errors
    CANNOT_ACCESS_PROPERTY = "E1012"
    CANNOT_SET_PROPERTY = "E1014"

    # Indexing errors
    OBJECT_IS_NOT_INDEXABLE = "E1013"
    INVALID_INDEX = "E1016"
    ARRAY_INVALID_INDEX = "E1017"
    STRING_INVALID_INDEX = "E1018"
    INVALID_INDEX_TYPE = "E1023"

    # Method errors
    OBJECT_NOT_CALLABLE = "E1020"
    INVALID_ARGUMENT_COUNT = "E1021"
    DUPLICATE_PARAMETER = "E1022"

    # Parser errors
    SYNTAX_ERROR = "E2000"
    UNEXPECTED_TOKEN = "E2001"
    RETURN_OUTSIDE_FUNCTION = "E2002"
    CONTINUE_OUTSIDE_LOOP = "E2003"
    BREAK_OUTSIDE_LOOP = "E2004"
    INVALID_ASSIGNMENT_TARGET = "E2005"
    UNEXPECTED_END_OF_INPUT = "E2006"
    INVALID_DEFAULT_CREATION = "E2007"

    # Lexer errors
    INVALID_CHARACTER = "E3000"
    UNTERMINATED_STRING = "E3001"
    INVALID_ESCAPE_SEQUENCE = "E3002"

    # Module errors
    MODULE_NOT_FOUND = "E4000"
    CIRCULAR_MODULE_DEPENDENCY = "E4001"

    # CLI errors
    MISSING_FILENAME = "E5000"
    INVALID_FILE_TYPE = "E5001"